server:
  port: 8080


# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


# MyBatis的mapper.xml路径配置
mybatis:
  mapper-locations:
    classpath: mapper/*.xml
    classpath*: edu/**/mapper/*.xml


# 日志配置
logging:
  level:
    root: INFO
    edu.zju.cst.bookstore: DEBUG


